# Generated by Django 4.2.7 on 2025-09-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='about',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='picture',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
