# Generated by Django 4.2.7 on 2025-10-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0002_alter_register_about_alter_register_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='lastane',
            new_name='lastname',
        ),
    ]
