# Generated by Django 4.2.7 on 2025-10-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0003_rename_lastane_register_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='MakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedStartDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('watcher_role', models.TextField()),
                ('rate_hour', models.CharField(max_length=255)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mother_app.register')),
            ],
        ),
    ]
