# Generated by Django 4.2.7 on 2025-10-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0004_alter_register_email_makerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='child_option',
            field=models.CharField(default='', max_length=255),
        ),
    ]
