# Generated by Django 4.2.7 on 2025-10-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0005_makerequest_child_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequest',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='endTime',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='rate_hour',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='selectedStartDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='startTime',
            field=models.CharField(default='', max_length=255),
        ),
    ]
