# Generated by Django 4.2.7 on 2025-10-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0006_alter_makerequest_email_alter_makerequest_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('helpText', models.TextField()),
            ],
        ),
    ]
