# Generated by Django 4.2.7 on 2025-11-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0007_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=255)),
                ('dob', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('skills', models.TextField(default='', max_length=255)),
                ('about', models.TextField(default='', max_length=255)),
                ('picture', models.TextField(default='', max_length=255)),
                ('hour_rate', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
