# Generated by Django 4.2.7 on 2025-11-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0008_registerwatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerwatcher',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
