# Generated by Django 4.2.7 on 2025-11-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0009_registerwatcher_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
