# Generated by Django 4.2.7 on 2025-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0010_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='email',
        ),
        migrations.AddField(
            model_name='chats',
            name='received_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chats',
            name='sender_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
