# Generated by Django 5.2.5 on 2025-12-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0011_remove_chats_email_chats_received_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='email_to',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
