# Generated by Django 5.2.5 on 2025-12-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0012_makerequest_email_to_makerequest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
