# Generated by Django 5.2.5 on 2025-12-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0013_alter_makerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.BooleanField(default=False, max_length=255),
        ),
    ]
