# Generated by Django 5.2.5 on 2025-12-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0014_alter_makerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='child_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='mother_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
