# Generated by Django 5.2.5 on 2025-12-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0015_makerequest_child_no_makerequest_mother_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makerequest',
            old_name='child_option',
            new_name='child_option2',
        ),
    ]
