# Generated by Django 5.2.5 on 2025-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0016_rename_child_option_makerequest_child_option2'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerwatcher',
            name='cpr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerwatcher',
            name='firstaid',
            field=models.BooleanField(default=False),
        ),
    ]
