# Generated by Django 5.2.5 on 2026-01-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0017_registerwatcher_cpr_registerwatcher_firstaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='makerequest',
            name='zipcode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
