# Generated by Django 5.2.5 on 2026-01-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0018_makerequest_address_makerequest_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('address1', models.CharField(default='', max_length=255)),
                ('address2', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('zipcode', models.CharField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=255)),
                ('cardnumber', models.CharField(default='', max_length=255)),
                ('expirationdate', models.CharField(default='', max_length=255)),
                ('cvv', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
