# Generated by Django 5.2.5 on 2026-01-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0019_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerwatcher',
            name='backcheck',
            field=models.BooleanField(default=False),
        ),
    ]
