# Generated by Django 5.2.5 on 2026-01-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0020_registerwatcher_backcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
