# Generated by Django 5.2.5 on 2026-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0021_makerequest_confirm_alter_makerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='picture',
            field=models.TextField(default=''),
        ),
    ]
