# Generated by Django 5.2.5 on 2026-01-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0022_makerequest_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='picture2',
            field=models.TextField(default=''),
        ),
    ]
