# Generated by Django 5.2.5 on 2026-01-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0023_makerequest_picture2'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerequest',
            name='watcher_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
