# Generated by Django 5.2.5 on 2026-01-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0024_makerequest_watcher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequest',
            name='email_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
