# Generated by Django 5.2.5 on 2026-01-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0025_alter_makerequest_email_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
