# Generated by Django 5.2.5 on 2026-01-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0026_cards_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendemail', models.BooleanField(default=False)),
                ('sendphone', models.BooleanField(default=False)),
                ('no', models.BooleanField(default=False)),
                ('email', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
