# Generated by Django 5.2.5 on 2026-01-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0027_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='register',
            name='no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='sendemail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='sendphone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerwatcher',
            name='no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerwatcher',
            name='sendemail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerwatcher',
            name='sendphone',
            field=models.BooleanField(default=False),
        ),
    ]
