# Generated by Django 4.2.7 on 2026-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0029_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='plan',
            field=models.CharField(default='', max_length=255),
        ),
    ]
