# Generated by Django 4.2.7 on 2026-03-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0030_cards_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
