# Generated by Django 4.2.7 on 2026-03-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0032_alter_cards_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='customer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='register',
            name='payment_method',
            field=models.CharField(default='', max_length=255),
        ),
    ]
