# Generated by Django 4.2.7 on 2026-03-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0034_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='stripe_payment_id',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
