# Generated by Django 4.2.7 on 2026-03-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0035_rename_stripe_payment_id_payments_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='user_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='payments',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
