# Generated by Django 4.2.7 on 2026-03-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0036_rename_user_email_payments_email_payments_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='request_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
