# Generated by Django 4.2.7 on 2026-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mother_app', '0037_alter_payments_amount_alter_payments_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='to_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
